name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  create:
    tags:
      - v*

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run tests
        run: go test ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.52

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: go build -o my-cli-project

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-cli-project
          path: my-cli-project
